### ISSUE TITLE
Add time to win message

### ISSUE THREAD

**Issue by zozs** [zozs/a-wild-button-appears#1]
Add the time to the message printed when a user has won, similar to:

> @linus won (1.56 s)!

**Comment by linus** [comment]
I won?! Is there a sweet :medal_military:?

**Comment by zozs** [comment]
_Note to self:_ Remember to replace my Slack username with my own Github username in future issues :sweat_smile: 

_Also_: Bonus honorary medal to @linus :medal_military:. You are now an honorary member of a Slack bot you've never used. Congratulations! :confetti_ball:

**Comment by linus** [comment]
:unicorn: :panda_face: :white_flower:
